resolver: nightly-2016-06-03
packages:
- '.'
- location:
    git: https://github.com/ekmett/bits.git
    commit: 415324c782b2a374d1b84503d18f8cca5678049b
extra-deps: []
flags:
  bits:
    test-doctests: false
extra-package-dbs: []
